'use client';
import {useEffect,useState, type FormEvent} from 'react';
import {Upload,ArrowLeft,Shield,LogOut,FileSpreadsheet,CheckCircle2} from 'lucide-react';
import {formatMinutes,EVENT,type Learner} from '@/lib/rules';
type Data={demo:boolean;asOf:string|null;updatedAt:string|null;recommendedUrl:string;learners:Learner[]};
type Preview={preview:{learners:number;courseRows:number;duplicateRows:number;totalMinutes:number};revision:number;hash:string};
export default function Admin({initialAuthenticated,configured}:{initialAuthenticated:boolean;configured:boolean}){
  const [auth,setAuth]=useState(initialAuthenticated),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[data,setData]=useState<Data|null>(null),[file,setFile]=useState<File|null>(null),[end,setEnd]=useState(''),[confirmed,setConfirmed]=useState(false),[preview,setPreview]=useState<Preview|null>(null),[url,setUrl]=useState(''),[search,setSearch]=useState('');
  async function reload(){const r=await fetch('/api/admin/data',{cache:'no-store'});const v=await r.json();if(!r.ok)throw new Error(v.error);setData(v);setUrl(v.recommendedUrl);}
  useEffect(()=>{if(auth)void reload().catch(e=>setMessage(e.message));},[auth]);
  async function login(e:FormEvent){e.preventDefault();setBusy(true);setMessage('');try{const r=await fetch('/api/admin/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password})});const v=await r.json();if(!r.ok)throw new Error(v.error);setPassword('');setAuth(true);}catch(e){setMessage(e instanceof Error?e.message:'로그인 실패');}finally{setBusy(false);}}
  async function upload(commit=false){if(!file)return;setBusy(true);setMessage('');try{const form=new FormData();form.set('file',file);form.set('start',EVENT.start);form.set('end',end);form.set('confirmed',String(confirmed));form.set('action',commit?'commit':'preview');if(preview){form.set('revision',String(preview.revision));form.set('hash',preview.hash);}const r=await fetch('/api/admin/upload',{method:'POST',body:form});const v=await r.json();if(!r.ok)throw new Error(v.error);if(commit){setPreview(null);setMessage('전체 학습 데이터와 랭킹이 업데이트되었습니다.');await reload();}else setPreview(v);}catch(e){setMessage(e instanceof Error?e.message:'업로드 실패');}finally{setBusy(false);}}
  async function saveLink(e:FormEvent){e.preventDefault();setBusy(true);try{const r=await fetch('/api/admin/settings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({url})});const v=await r.json();if(!r.ok)throw new Error(v.error);setMessage('추천 강의 링크를 저장했습니다.');}catch(e){setMessage(e instanceof Error?e.message:'저장 실패');}finally{setBusy(false);}}
  return <div className="admin-shell"><header className="header"><a className="brand" href="/">APR<span className="brand-line"/>EVENT ADMIN</a><a href="/" className="back-link"><ArrowLeft size={16}/> 학습자 화면</a></header><main><div className="intro"><div><div className="eyebrow"><Shield size={16}/> ADMIN CONSOLE</div><h1>이벤트 운영 관리</h1><p>학습 데이터를 업데이트하고 전체 랭킹을 확인하세요.</p></div>{auth&&<button className="secondary-button" onClick={async()=>{await fetch('/api/admin/logout',{method:'POST'});setAuth(false);setData(null);}}><LogOut size={16}/> 로그아웃</button>}</div>
    {!auth?<section className="login-card"><Shield size={28}/><h2>관리자 로그인</h2><p>등록된 이메일과 비밀번호를 입력하세요.</p>{!configured&&<div className="notice">관리자 계정과 데이터베이스 연결을 준비 중입니다. 설정 완료 후 로그인할 수 있습니다.</div>}<form onSubmit={login}><label htmlFor="admin-email">이메일</label><input id="admin-email" type="email" required value={email} autoComplete="username" onChange={e=>setEmail(e.target.value)}/><label htmlFor="password">비밀번호</label><input id="password" type="password" required value={password} autoComplete="current-password" onChange={e=>setPassword(e.target.value)}/><button className="primary-button" disabled={busy||!configured}>{busy?'로그인 중…':'로그인'}</button></form></section>:<>
      {data?.demo&&<div className="notice">현재 가상 데이터 미리보기 모드입니다. 실제 업로드와 링크 저장은 운영 모드로 전환한 후 사용할 수 있습니다.</div>}
      <div className="admin-grid"><section className="admin-card"><div className="eyebrow"><Upload size={16}/> DAILY UPDATE</div><h2>학습 보고서 업로드</h2><p>Udemy에서 <b>10/6부터 집계일까지</b>의 누적 보고서를 내려받아 주세요. 매번 전체 데이터를 교체합니다.</p><label className="upload-zone"><FileSpreadsheet size={32}/><strong>{file?.name??'CSV 또는 XLSX 파일 선택'}</strong><span>원본 보고서 · 최대 3MB</span><input type="file" accept=".csv,.xlsx" onChange={e=>{setFile(e.target.files?.[0]??null);setPreview(null);}}/></label><label htmlFor="asof">보고서 집계 종료일</label><input id="asof" type="date" min={EVENT.start} max={EVENT.end} value={end} onChange={e=>{setEnd(e.target.value);setPreview(null);}}/><label className="checkbox-label"><input type="checkbox" checked={confirmed} onChange={e=>{setConfirmed(e.target.checked);setPreview(null);}}/>10/6부터 선택한 종료일까지, 모든 강의를 포함한 전체 사용자 보고서임을 확인했습니다.</label><button className="primary-button" disabled={busy||!file||!end||!confirmed||data?.demo} onClick={()=>upload(false)}>{busy?'처리 중…':'파일 검증하기'}</button>
      {preview&&<div className="import-preview"><h3><CheckCircle2 size={18}/> 반영 전 확인</h3><p>{preview.preview.learners}명 · {preview.preview.courseRows}개 학습 기록<br/>총 {formatMinutes(preview.preview.totalMinutes)}<br/>동일한 중복 행 {preview.preview.duplicateRows}개 제외</p><p>현재 전체 랭킹을 이 보고서로 교체합니다.</p><button className="primary-button" disabled={busy} onClick={()=>upload(true)}>확인한 데이터로 전체 반영</button></div>}</section>
      <div className="side-stack"><section className="admin-card"><div className="eyebrow">UPDATE STATUS</div><h2>{data?.asOf??'업로드 대기'}</h2><p>학습 데이터 기준일</p><div className="admin-stat"><strong>{data?.learners.length??0}</strong><span>집계된 학습자</span></div><p>최근 반영: {data?.updatedAt?new Date(data.updatedAt).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'}):'—'}</p></section><section className="admin-card"><h2>추천 강의 링크</h2><p>링크를 추가하면 학습자 화면에 바로 표시됩니다.</p><form onSubmit={saveLink}><label htmlFor="recommend-url">추천 강의 모음 URL</label><input id="recommend-url" type="url" placeholder="https://" value={url} onChange={e=>setUrl(e.target.value)}/><button className="secondary-button" disabled={busy||data?.demo}>링크 저장</button></form></section></div></div>
      <section className="admin-card admin-ranking"><div className="section-heading"><h2>전체 랭킹</h2><input aria-label="이메일 검색" placeholder="이메일로 검색" value={search} onChange={e=>setSearch(e.target.value)}/></div><div className="table-wrap"><table><thead><tr><th>순위</th><th>이메일</th><th>공개 별칭</th><th>레벨</th><th>누적 학습</th><th>추첨 구간</th></tr></thead><tbody>{data?.learners.filter(p=>p.email.includes(search.toLowerCase())).map(p=><tr key={p.email}><td>{p.rank}</td><td>{p.email}</td><td>{p.alias}</td><td>Lv.{p.level}</td><td>{formatMinutes(p.minutes)}</td><td>{p.minutes<15?'조건 미달성':p.level===1?'커피':p.level===2?'배민':'디바이스'}</td></tr>)}</tbody></table></div>{data?.learners.length===0&&<p>업로드된 학습자가 없습니다.</p>}</section>
    </>}{message&&<div role="status" className="notice admin-message">{message}</div>}</main></div>;
}
