'use client';
import {useEffect,useState, type FormEvent} from 'react';
import {ArrowUpRight,ArrowRight,ChevronRight,BookOpen,Trophy,Clock3,Mail,Shield,Flame,Sparkles,Check,Search} from 'lucide-react';
import {REWARDS,progression,formatMinutes, type Learner} from '@/lib/rules';
type Player=Omit<Learner,'email'>;
type Board={demo:boolean;reportTest?:boolean;reportStart?:string|null;asOf:string|null;updatedAt:string|null;recommendedUrl:string;learners:Player[]};
const demoEmail='learner@apr-demo.example';
export default function Dashboard(){
  const [board,setBoard]=useState<Board|null>(null),[email,setEmail]=useState(''),[me,setMe]=useState<Player|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(false),[boardError,setBoardError]=useState('');
  async function load(){setBoardError('');try{const r=await fetch('/api/board',{cache:'no-store'});const v=await r.json();if(!r.ok)throw new Error(v.error);setBoard(v);}catch{setBoardError('랭킹을 불러오지 못했습니다. 잠시 후 다시 시도해 주세요.');}}
  useEffect(()=>{void load();},[]);
  async function lookup(e?:FormEvent,sample=false){e?.preventDefault();setError('');setLoading(true);setMe(null);const value=sample?demoEmail:email;if(sample)setEmail(demoEmail);
    try{const r=await fetch('/api/lookup',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:value})});const v=await r.json();if(!r.ok)throw new Error(v.error);setMe(v.learner);}catch(e){setError(e instanceof Error?e.message:'조회에 실패했습니다.');}finally{setLoading(false);}
  }
  const progress=progression(me?.minutes??0);
  const reward=me&&me.minutes>=15?REWARDS[me.level-1]:null;
  return <div className="site-shell">
    <header className="header"><a href="/" className="brand">APR<span className="brand-line"/>LEARNING EVENT</a><nav><a href="#rewards">리워드</a><a href="#ranking">랭킹</a><a className="course-link" href="https://apr.udemy.com" target="_blank" rel="noreferrer">학습하러 가기 <ArrowUpRight size={16}/></a></nav></header>
    <main>
      <section className="intro"><div><div className="eyebrow"><span className="small-rule"/>2026. 10 APR LEARNING EVENT</div><h1>APR, 나혼자만 <span>레벨업</span><span className="title-square">↗</span></h1><p>오늘의 학습이, 내일의 레벨이 된다.</p></div><div className="event-period"><span>EVENT PERIOD</span><strong>10.06 <i>—</i> 10.28</strong><small>모든 Udemy 강의 학습시간 인정</small></div></section>
      <div className="main-grid">
        <section className="player-panel"><div className="panel-heading"><div className="eyebrow"><Shield size={16}/> MY STATUS</div><span className="status-tag">{me?'조회 완료':'플레이어 조회'}</span></div>
          <div className="status-content"><div className={'level-emblem level-'+(me?.level??0)}><span>LEVEL</span><strong>{me?.level??'00'}</strong><small>{me?.level===3?'MASTER':me?.level===2?'CHALLENGER':'ROOKIE'}</small></div><div className="player-copy"><p className="muted">{me?me.alias:'나의 학습 여정'}</p><h2>{me?(me.level===3?'최고 레벨 달성!':`Lv.${me.level}, 다음 단계로!`):'지금, 내 레벨은?'}</h2><p>{me?(reward?`${reward.title} 추첨 대상입니다.`:'15분 학습하면 첫 리워드에 도전할 수 있어요.'):'Udemy 로그인 이메일로\n나의 성장 기록을 확인하세요.'}</p>{me&&<div className="personal-stats"><span><Clock3 size={16}/> {formatMinutes(me.minutes)}</span><span><Trophy size={16}/> {me.rank}위</span></div>}</div></div>
          <form onSubmit={lookup} className="lookup-form"><label htmlFor="email">Udemy 로그인 이메일</label><div className="input-group"><Mail size={19}/><input id="email" type="email" required maxLength={254} placeholder="이메일 주소를 입력하세요" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)}/><button disabled={loading}>{loading?'조회 중…':'내 레벨 확인'}<ArrowRight size={17}/></button></div><div className="lookup-feedback" aria-live="polite">{error&&<p className="error">{error}</p>}</div></form>
          <div className="exp-block"><div><span>EXP <b>{me?formatMinutes(me.minutes):'학습으로 경험치를 쌓으세요'}</b></span><span>{me?.level===3?'MAX LEVEL':`${progress.target}분 목표`}</span></div><div className="exp-track" role="progressbar" aria-label="다음 학습 목표 진행률" aria-valuemin={0} aria-valuemax={100} aria-valuenow={me?Math.round(progress.percent):0}><span style={{width:`${me?progress.percent:0}%`}}/></div><p>{me?(progress.remaining>0?`다음 목표까지 ${formatMinutes(progress.remaining)} 남았어요.`:'최고 레벨에 도달했어요. 학습을 이어가며 랭킹에 도전하세요.'):'Lv.0에서 시작해, 15분에 Lv.1 · 60분에 Lv.2 · 120분에 Lv.3으로 성장합니다.'}</p></div>
        </section>
        <aside className="quest-panel"><div className="eyebrow"><Flame size={16}/> LEVEL UP EVENT</div><h2>작은 몰입,<br/>더 큰 성장.</h2><div className="quest-path">{[{min:15,title:'Lv.1 · 첫 리워드 달성',desc:'커피 한 잔의 여유'},{min:60,title:'Lv.2로 레벨업',desc:'맛있는 한 끼의 보상'},{min:120,title:'Lv.3 최고 레벨',desc:'메디큐브 부스터 글로우에 도전'}].map((q,i)=><div className={'quest-step '+(me&&me.minutes>=q.min?'done':'')} key={q.min}><span className="step-icon">{me&&me.minutes>=q.min?<Check size={18}/>:String(i+1).padStart(2,'0')}</span><div><h3>{q.title}</h3><p>{q.desc}</p></div><b>{q.min}분</b></div>)}</div><a href="https://apr.udemy.com" target="_blank" rel="noreferrer" className="primary-button">Udemy에서 학습 시작 <ArrowUpRight size={18}/></a></aside>
      </div>
      <section id="rewards" className="section"><div className="section-heading"><div><div className="eyebrow">REWARD INVENTORY</div><h2>성장한 만큼, 가까워지는 리워드</h2></div><span className="section-note">최종 레벨별 추첨 · 총 16명</span></div><div className="reward-grid">{REWARDS.map((r,i)=><article key={r.level} className={'reward-card tier-'+r.level+' '+(reward?.level===r.level?'unlocked':'')}><div className="reward-top"><span className="tier-label">Lv.{r.level}</span><span>{r.count}명 추첨</span></div><div className="reward-icon">{i===0?<BookOpen size={36} strokeWidth={1.4}/>:i===1?<Flame size={36} strokeWidth={1.4}/>:<Sparkles size={36} strokeWidth={1.4}/>}</div><p className="reward-range">{r.range}</p><h3>{r.title}</h3>{r.detail && <strong>{r.detail}</strong>}<div className="reward-foot">{reward?.level===r.level?<><Check size={15}/> 현재 추첨 대상</>:<><span>학습하고 도전하기</span><ChevronRight size={16}/></>}</div></article>)}</div><p className="fineprint">10/28 종료 시 최종 레벨에 해당하는 구간에서만 추첨합니다. 상위 구간 미당첨자는 하위 구간 추첨에 포함되지 않습니다. 15분 미만은 추첨 대상에서 제외됩니다.</p></section>
      <div className="bottom-grid"><section id="ranking" className="ranking-panel"><div className="section-heading"><div><div className="eyebrow">LEADERBOARD</div><h2>함께 달리는 플레이어</h2></div><span className="section-note">{board?.learners.length??'—'}명 참여</span></div><div className="rank-meta"><span><Clock3 size={14}/>{board?.asOf?`${board.demo?'가상 데이터 · ':board.reportTest?'보고서 테스트 · ':''}${board.asOf} 학습 데이터 기준`:'아직 집계된 데이터가 없습니다'}</span><span>매일 업데이트</span></div>
        {boardError?<div className="empty-state"><p>{boardError}</p><button onClick={load}>다시 불러오기</button></div>:!board?<div className="empty-state">랭킹을 불러오는 중입니다…</div>:!board.learners.length?<div className="empty-state"><Trophy/><h3>첫 번째 랭킹을 기다리고 있어요</h3><p>학습 기록이 업데이트되면 이곳에서 확인할 수 있습니다.</p></div>:<div className="table-wrap"><table><thead><tr><th>순위</th><th>플레이어</th><th>레벨</th><th className="right">누적 학습</th></tr></thead><tbody>{board.learners.map(p=><tr key={p.alias} className={me?.alias===p.alias?'my-row':''}><td><span className={'rank-number rank-'+p.rank}>{p.rank<=3?<Trophy size={15}/>:null}{p.rank}</span></td><td>{p.alias}{me?.alias===p.alias&&<span className="you-tag">나</span>}</td><td><span className={'level-chip chip-'+p.level}>Lv.{p.level}</span></td><td className="right">{formatMinutes(p.minutes)}</td></tr>)}</tbody></table></div>}<p className="fineprint">누적 학습시간 기준 · 동점자는 공동 순위 · 개인정보 보호를 위해 별칭 표시</p></section>
        <aside className="side-stack"><section className="recommend-panel"><BookOpen size={25}/><div className="eyebrow">NEXT LEARNING</div><h2>다음 레벨을 위한<br/>새로운 배움</h2><p>3분기 추천 강의와 직무별 강의를<br/>한곳에서 만나보세요.</p>{board?.recommendedUrl?<a href={board.recommendedUrl} target="_blank" rel="noreferrer">추천 강의 모아보기 <ArrowUpRight size={17}/></a>:<div className="pending-link">추천 강의 리스트 준비 중</div>}</section><section className="guide-panel"><h3>참여 전 확인하세요</h3><ul><li>이벤트 기간: 2026.10.06~10.28</li><li>APR Udemy의 모든 강의가 대상입니다.</li><li>학습시간은 실시간으로 반영되지 않습니다.</li><li>이메일 조회로 레벨·시간·순위를 확인할 수 있습니다.</li></ul></section></aside></div>
    </main><footer><a href="/" className="footer-brand">APR <span>LEARNING EVENT</span></a><p>배움의 기록이 나의 레벨이 되는 곳.</p><a href="/admin">관리자 <Shield size={14}/></a></footer>
  </div>;
}
